### ISSUE TITLE
请问为什么编译完运行不了

### ISSUE THREAD

**Issue by upupbo** [pkufool/cppinyin#1]
![Uploading 微信图片_20240924112102.png…]()

**Comment by upupbo** [comment]
![微信图片_20240924112102](https://github.com/user-attachments/assets/b037b61c-567b-4557-9ffd-58ef60c23a03)

**Comment by pkufool** [comment]
这是 python 包， 命令行是python打包的命令，你得用 `pip install cppinyin` 才能用命令行工具。
